---
- name: ultrasonic
  hosts: localhost
  gather_facts: no
  connection: local
  become: True

  tasks:
    - name: "Install pip dependencies"
      pip:
        name: RPi.GPIO
        version: 0.7.0 
